# Set the default log level of this plugin
# Should be one of: ALL FINEST FINER FINE INFO WARNING SEVERE OFF
log-level: INFO

# Name of the template world that will be copied to generate new instances
# Should be all lowercase
template-world-name: template

# Base name of instanced worlds. Worlds will be named <basename>-# (i.e. instance-1, instance-2, etc.)
# Should be all lowercase
base-world-name: instance

# Whether or not this server should automatically manage world instances.
# If set to false this plugin will only provide world management commands / API
# If set to true, this plugin will automatically load, unload, and manage worlds based on player instance scores
is-instanced: false

# If set to true and a world joins with an instance score that doesn't already have a corresponding world,
# a new world will be copied & loaded automatically from the template world
allow-instance-autocreation: true

# Number of instances to pre-generate so they are available when a player joins
# When the server starts up for the first time with no existing instances, this many instances will be generated immediately as async tasks
# After that, when a player joins within the last # instances, more instances will be generated to maintain this number of never-joined instances afterwards
# Highly recommended to use this to significantly decrease world loading wait times to get new instances
# Set to 0 to disable
pregenerated-instances: 0

# MonumentaRedisSync rboard name to use to determine what the latest used instance is for pregeneration
# If either is null, pregeneration will assume instances start at 0
# the rboard is a hashmap - so name of the hashmap, then the key in that hashmap with the integer value of the last used instance
pregenerated-rboard-name: null
pregenerated-rboard-key: null

# The scoreboard objective used to determine what world instance a player should be sent to
instance-objective: Instance

# After how many ticks of no players should a world be unloaded?
# This setting only takes effect if is-instanced is true
# Will not unload the primary world
# Set to <= 0 to disable automatic unloading
# The system that manages this checks world activity every 10s
unload-inactive-world-after-ticks: 12000

# Command to run on players when they join an instanced world for the first time (useful for instance autocreation)
# This will be run via the console like: /execute as <player> at @s run <command>
# Set to null to disable
join-instance-command: null

# Command to run on players when they re-join an instanced world after having been there before
# This will be run via the console like: /execute as <player> at @s run <command>
# Set to null to disable
rejoin-instance-command: null

# Notify players with this permission which world they are on when they join
# Set to null to disable
notify-world-permission: "monumenta.worldmanagement.worldnotify"

# Command used to create worlds (by copying them).
# Will be executed via the shell in the server directory like "command srcWorld destWorld"
# Note that the default here (cp -a) will only work on Linux and Mac
# If the world contains entities, those entities will have the same UUID as in the source world and they will conflict
# This is normally fine as Spigot will assign them new UUIDs when the conflict is detected
# The exception to this is if any entities are assigned scoreboard values, in which case they may be lost / behave strangely
# Ideally this would be set to a tool that can copy the worlds and generate new UUIDs for entities
#   For example use https://github.com/TeamMonumenta/monumenta-automation/blob/master/utility_code/copy_world.py
copy-world-command: "cp -a"
