[versions]
commandapi = "9.4.1"
redissync = "4.1"
gson = "2.8.5"

[libraries]
commandapi = { module = "dev.jorel:commandapi-bukkit-core", version.ref = "commandapi" }
redissync = { module = "com.playmonumenta:redissync", version.ref = "redissync" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
